import { getCurrentMember } from "@/lib/auth";

const rolePermissionMap: Record<string, string[]> = {
  owner: ["*"],
  admin: [
    "organization.manage",
    "modules.manage",
    "approvals.manage",
    "logs.read",
    "events.read",
    "files.manage",
    "ai.manage",
    "agents.manage",
    "finance.view",
    "finance.create",
    "finance.update",
    "finance.delete",
    "finance.approve",
    "finance.export",
    "finance.view_all",
    "finance.category.manage",
    "finance.account.manage",
    "finance.ai_parse",
    "projects.view",
    "projects.manage",
    "tasks.view",
    "tasks.create",
    "tasks.update",
    "tasks.delete",
    "tasks.comment",
    "tasks.files",
    "tasks.archive",
    "governance.view",
    "governance.manage",
    "risk_rule.view",
    "risk_rule.manage",
    "knowledge.view",
    "knowledge.manage",
    "sop.view",
    "sop.create",
    "sop.update",
    "review.view",
    "review.create",
    "review.update",
    "evolution.view",
    "evolution.manage",
    "feedback.view",
    "feedback.create",
    "review_record.view",
    "review_record.create",
    "sop_record.view",
    "sop_record.create",
    "improvement.view",
    "improvement.manage",
    "ai_workforce.view",
    "ai_workforce.manage",
    "agent.view",
    "agent.manage",
    "agent.create",
    "agent.update",
    "agent.pause",
    "agent.archive",
    "agent.run",
    "agent.view_logs",
    "prompt.view",
    "prompt.manage",
    "prompt.create",
    "prompt.update",
    "prompt.publish",
    "prompt.archive",
    "prompt.test",
    "ai_confirmation.view",
    "ai_confirmation.approve",
    "ai_confirmation.reject",
    "ai_feedback.create",
    "ai_feedback.view"
  ],
  manager: [
    "approvals.manage",
    "logs.read",
    "events.read",
    "files.manage",
    "agents.manage",
    "finance.view",
    "finance.create",
    "finance.update",
    "finance.approve",
    "finance.export",
    "finance.view_team",
    "finance.ai_parse",
    "projects.view",
    "projects.manage",
    "tasks.view",
    "tasks.create",
    "tasks.update",
    "tasks.comment",
    "tasks.files",
    "tasks.archive",
    "governance.view",
    "knowledge.view",
    "sop.view",
    "sop.create",
    "sop.update",
    "review.view",
    "review.create",
    "review.update",
    "evolution.view",
    "feedback.view",
    "feedback.create",
    "review_record.view",
    "review_record.create",
    "sop_record.view",
    "sop_record.create",
    "improvement.view",
    "ai_workforce.view",
    "agent.view",
    "agent.create",
    "agent.update",
    "agent.pause",
    "agent.archive",
    "agent.run",
    "agent.view_logs",
    "prompt.view",
    "prompt.create",
    "prompt.update",
    "prompt.publish",
    "prompt.archive",
    "prompt.test",
    "ai_confirmation.view",
    "ai_confirmation.approve",
    "ai_confirmation.reject",
    "ai_feedback.create",
    "ai_feedback.view"
  ],
  member: [
    "dashboard.read",
    "approvals.create",
    "files.manage",
    "finance.view",
    "finance.create",
    "finance.update",
    "finance.export",
    "finance.ai_parse",
    "projects.view",
    "tasks.view",
    "tasks.comment",
    "tasks.files",
    "knowledge.view",
    "sop.view",
    "review.view",
    "evolution.view",
    "feedback.view",
    "feedback.create",
    "review_record.view",
    "sop_record.view",
    "ai_workforce.view",
    "agent.view",
    "agent.run",
    "prompt.view",
    "prompt.create",
    "prompt.test",
    "ai_feedback.create"
  ],
  agent: ["dashboard.read", "files.read", "finance.view", "projects.view", "tasks.view", "knowledge.view", "evolution.view", "feedback.create", "ai_workforce.view", "agent.view", "agent.run", "ai_feedback.create"]
};

export async function hasPermission(permissionKey: string) {
  const member = await getCurrentMember();
  const roleKey = member.role?.key ?? "member";
  const permissions = rolePermissionMap[roleKey] ?? [];
  return permissions.includes("*") || permissions.includes(permissionKey);
}

export async function canAccessModule(requiredPermission: string) {
  if (requiredPermission.endsWith(".read")) return true;
  return hasPermission(requiredPermission);
}

export async function requirePermission(permissionKey: string) {
  const allowed = await hasPermission(permissionKey);
  if (!allowed) {
    throw new Error(`Missing permission: ${permissionKey}`);
  }
}

export function getRolePermissionKeys(roleKey: string) {
  return rolePermissionMap[roleKey] ?? [];
}
